cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      logged_in: false
      name: John Smith
      password: $2b$12$qgpdymNsKCf9Hjwg.NSXiO9/ItCdKVNoJBWQf6EAk9n73HgkAJmEC
      role: admin
    nirmal2745:
      email: nirmalpandey048@gmail.com
      failed_login_attempts: 0
      first_name: Nirmal
      last_name: Pandey
      logged_in: true
      password: $2b$12$VVM6BOlhMVH3GFNV4evmVu6fi6JT.G57iij0F630VZh1aQ0qeYkI.
      password_hint: bange
      roles: null
    rbriggs:
      email: rbriggs@gmail.com
      logged_in: false
      name: Rebecca Briggs
      password: $2b$12$uON60sh.2IdIk4cka2YILuRo4kQai.pU8McK/owmmJ.QawK85GrdK
      role: user
preauthorized:
  emails:
  - melsby@gmail.com
